### ISSUE TITLE
auth jwt token from any variable

### ISSUE THREAD

**Issue by RekGRpth** [maxam18/nginx-ejwt-module#3]
How auth jwt token from any variable, like in https://github.com/max-lt/nginx-jwt-module ?

**Comment by maxam18** [comment]
You can use any JWT claim field (but only at first level of JSON) to check auth. The _name_ of the field is the string. The value can contain nginx variables.
```
easy_jwt_key  HS256  'Secret';
location /check_auth_by_uri {
        easy_jwt hs256;
        easy_jwt_auth "uri" '$request_uri';
}
```
# Make JWT
## Header: 
```
{
  "alg": "HS256",
  "typ": "JWT"
}
```
## Claim
```
{
  "sub": "1234567890",
  "name": "John Doe",
  "iat": 1516239022,
  "uri": "/check_auth_by_uri"
}
```
# Check your configuration:

`curl -D - -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyLCJ1cmkiOiIvY2hlY2tfYXV0aF9ieV91cmkifQ.iQsP_0v7LuxzSItvE9fBnkZuF7zHvkWePcqG4FZkgII' http://<HOST>/check_auth_by_uri`

This makes two checks:
1. Check JWT signature (authentication)
2. Check the "uri" field in JWT claim equals to the requested URI

**Comment by RekGRpth** [comment]
No, I mean, get jwt token from any variable, not only Authorization: Bearer and Cookie

**Comment by RekGRpth** [comment]
For example
```nginx
easy_jwt hmac $cookie_token;
```

**Comment by RekGRpth** [comment]
or
```nginx
easy_jwt hmac $http_authorization;
```

**Comment by maxam18** [comment]
If you don't specify _easy_jwt_auth_ the module will only checks the signature.

**Comment by maxam18** [comment]
Good thought. I will think about.

> 



> or
> 
> ```nginx
> easy_jwt hmac $http_authorization;
> ```

Good thought. Thanks. I'll think of it.

**Comment by RekGRpth** [comment]
You get jwt from Authorization: Bearer or from Cookie
But I suggest to take it from any variable (including $http_authorization for Authorization: Bearer and $cookie_token for Cookie)

**Comment by RekGRpth** [comment]
and You not need command "easy_jwt_cookie"

**Comment by maxam18** [comment]
> You get jwt from Authorization: Bearer or from Cookie But I suggest to take it from any variable (including $http_authorization for Authorization: Bearer and $cookie_token for Cookie)

Yes. I've got an idea. 
Should we answer with "WWW-Authenticate" in the case of token is in the variable? What do you think?

**Comment by maxam18** [comment]
> and You not need command "easy_jwt_cookie"

Sure

**Comment by RekGRpth** [comment]
or You may make syntax compatible to https://nginx.org/en/docs/http/ngx_http_auth_jwt_module.html

**Comment by RekGRpth** [comment]
> Should we answer with "WWW-Authenticate" in the case of token is in the variable? What do you think?

No, I think, You may simply return NGX_HTTP_UNAUTHORIZED always

**Comment by RekGRpth** [comment]
NGX_HTTP_EJWT_MODE_PRASE -> NGX_HTTP_EJWT_MODE_PARSE ?

**Comment by maxam18** [comment]
> NGX_HTTP_EJWT_MODE_PRASE -> NGX_HTTP_EJWT_MODE_PARSE ?

This only parses JWT to extract variables. No auth.

**Comment by RekGRpth** [comment]
> > NGX_HTTP_EJWT_MODE_PRASE -> NGX_HTTP_EJWT_MODE_PARSE ?
> 
> This only parses JWT to extract variables. No auth.

it is just syntax mistake **PRASE**

**Comment by maxam18** [comment]
> it is just syntax mistake PRASE

Oeps. Thanks!

**Comment by maxam18** [comment]
I have filed two enhancement issues. Will do this weekend.
