### ISSUE TITLE
Introduce token from variable

### ISSUE THREAD

**Issue by maxam18** [maxam18/nginx-ejwt-module#4]
Change behaviour of the _easy_jwt_ parameter:

## easy_jwt - module operation mode
**Syntax**: `easy_jwt  mode [variable]`
**Default**: `mode=off`
**Context**: location

    Turns on module functionality.

    mode is one of
        off - module inactive (default)
        parse - only parses JWT
        hs256 - check JWT only HS256 signature if found in JWT
        rs256 - check JWT only RS256 signature if found in JWT
        hmac  - check JWT HMAC only signature if found in JWT (based on 'alg' from JWT header)
        pub   - check JWT priv/pub key signature if found in JWT (based on 'alg' from JWT header)
        all   - check JWT with any supported algorithms (based on 'alg' from JWT header)
    
    variable is a name of nginx variable to extract token from.
    
 `variable` also obsoletes `easy_jwt_cookie` directive. Since `variable` could be set to `$cookie_[name]`

**Comment by RekGRpth** [comment]
where is checking if second argument is given here?! https://github.com/maxam18/nginx-ejwt-module/blob/005f942213f3c6788fc1e8279bb0ee5e8d6cff6d/ngx_http_ejwt_module.c#L929

**Comment by RekGRpth** [comment]
another bug, found by `cppcheck -j"$(nproc)" --verbose --force --enable=all --suppress=variableScope`
```sh
ngx_http_ejwt_module.c:921:9: style: Redundant initialization for 'var'. The initialized value is overwritten before it is read. [redundantInitialization]
    var = cf->args->elts;
        ^
ngx_http_ejwt_module.c:919:44: note: var is initialized
    ngx_str_t                         *var = cf->args->elts;
                                           ^
ngx_http_ejwt_module.c:921:9: note: var is overwritten
    var = cf->args->elts;
        ^
```

**Comment by maxam18** [comment]
Thank you @RekGRpth !!!

**Comment by RekGRpth** [comment]
Thank you for token from variable
